# Generated by Django 3.1.2 on 2021-03-18 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=100)),
                ('balance', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_status', models.CharField(default='Pending', max_length=20)),
                ('transfer_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='transaction.customer')),
                ('transfer_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='transaction.customer')),
            ],
        ),
    ]
