# Generated by Django 3.1.2 on 2021-03-18 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transfer_to',
            new_name='credited_to',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transfer_from',
            new_name='debited_from',
        ),
    ]
