# Generated by Django 3.1.2 on 2021-03-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_auto_20210318_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='account_number',
            field=models.CharField(default=400, max_length=50),
            preserve_default=False,
        ),
    ]
